# Sample config file: https://github.com/dashingcode/front-cover/blob/master/_config.yml
# Site settings
name: Omar Sahl
description: "Hey, Iâ€™m a Software Engineer from Cairo, Egypt ðŸ‡ªðŸ‡¬"
description1: "Currently based in Novosibirsk, Russia ðŸ‡·ðŸ‡º"
description2: "Let's Get In Touch!"
url: "https://omarsahl.github.io/"
title: "Omar Sahl"

# Delete the lines you don't need
# about 5 elements are recomended
github_username:  omarsahl
facebook_username: omarsahlf
email: os@omarsahl.com
twitter_username: omarsahl_
linkedin_username: omarsahl
instagram_username: omarsahl_

avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars2.githubusercontent.com/u/20464116?v=3&s=460"

front_img: yes
front_img_path: "https://source.unsplash.com/deagK9-Dmt0/1920x1080"
#front_img_path: "https://external.url/image.jpg"

favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"

# Build settings
markdown: kramdown
permalink: pretty
